services:
  Customer.domain.CustomerRepository:
    class: ../../../../contexts/customer/infrastructure/persistence/TypeOrmCustomerRepository
    arguments: ['@Customer.Shared.ConnectionManager']

  Customer.application.CustomerCreator:
    class: ../../../../contexts/customer/application/create/CustomerCreator
    arguments: ['@Customer.domain.CustomerRepository', '@Customer.Shared.domain.EventBus']

  Customer.application.CustomerGetById:
    class: ../../../../contexts/customer/application/getById/CustomerGetById
    arguments: ['@Customer.domain.CustomerRepository']

  Customer.application.CustomerInactivator:
    class: ../../../../contexts/customer/application/inactivate/CustomerInactivator
    arguments: ['@Customer.domain.CustomerRepository', '@Customer.Shared.domain.EventBus']

  Customer.application.CustomerDeleter:
    class: ../../../../contexts/customer/application/delete/CustomerDeleter
    arguments: ['@Customer.domain.CustomerRepository', '@Customer.Shared.domain.EventBus']
