services:
  Customer.domain.CustomerRepository:
    class: ../../../../contexts/customer/infrastructure/persistence/TypeOrmCustomerRepository
    arguments: ['@Customer.Shared.ConnectionManager']

  Customer.application.CustomerCreator:
    class: ../../../../contexts/customer/application/create/CustomerCreator
    arguments: ['@Customer.domain.CustomerRepository', '@Customer.Shared.domain.EventBus']

  Customer.application.CustomerUpdater:
    class: ../../../../contexts/customer/application/update/CustomerUpdater
    arguments: ['@Customer.domain.CustomerRepository', '@Customer.Shared.domain.EventBus']

  Customer.application.CustomerDeleter:
    class: ../../../../contexts/customer/application/delete/CustomerDeleter
    arguments: ['@Customer.domain.CustomerRepository', '@Customer.Shared.domain.EventBus']
