services:
  Apps.customer.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.customer.controllers.CustomerPostController:
    class: ../../controllers/CustomerPostController
    arguments: ['@Customer.application.CustomerCreator']

  Apps.customer.controllers.CustomerPutController:
    class: ../../controllers/CustomerPutController
    arguments: ['@Customer.application.CustomerUpdater']

  Apps.customer.controllers.CustomerDeleteController:
    class: ../../controllers/CustomerDeleteController
    arguments: ['@Customer.application.CustomerDeleter']
