services:
  customer.shared.PostgreConfig:
    factory:
      class: ../../../../contexts/shared/infrastructure/persistence/postgre/TypeOrmConfigFactory
      method: 'createConfig'

  customer.shared.RabbitMQConfig:
    factory:
      class: ../../../../contexts/shared/infrastructure/rabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  customer.shared.domain.EventBus:
    factory:
      class: ../../../../contexts/shared/infrastructure/rabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@customer.shared.DomainEventFailoverPublisher',
        '@customer.shared.RabbitMQConnection',
        '@customer.shared.RabbitMQqueueFormatter',
        '@customer.shared.RabbitMQConfig'
      ]

  customer.shared.ConnectionManager:
    factory:
      class: ../../../../contexts/shared/infrastructure/persistence/typeorm/TypeOrmClientFactory
      method: 'createClient'
    arguments: ['customer', '@customer.shared.PostgreConfig']

  customer.shared.RabbitMQqueueFormatter:
    class: ../../../../contexts/shared/infrastructure/eventBus/rabbitMq/RabbitMQqueueFormatter
    arguments: ['customer']

  customer.shared.RabbitMQConnection:
    class: ../../../../contexts/shared/infrastructure/eventBus/rabbitMq/RabbitMqConnection
    arguments: ['@customer.shared.RabbitMQConfig']

  customer.shared.RabbitMQConfigurer:
    class: ../../../../contexts/shared/infrastructure/eventBus/rabbitMq/RabbitMQConfigurer
    arguments: ['@customer.shared.RabbitMQConnection', '@customer.shared.RabbitMQqueueFormatter']

  customer.shared.DomainEventFailoverPublisher:
    class: ../../../../contexts/shared/infrastructure/eventBus/domainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@customer.shared.ConnectionManager']

  customer.shared.CommandHandlers:
    class: ../../../../contexts/shared/infrastructure/commandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  customer.shared.domain.CommandBus:
    class: ../../../../contexts/shared/infrastructure/commandBus/InMemoryCommandBus
    arguments: ['@customer.shared.CommandHandlers']

  customer.shared.QueryHandlers:
    class: ../../../../contexts/shared/infrastructure/queryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  customer.shared.domain.QueryBus:
    class: ../../../../contexts/shared/infrastructure/queryBus/InMemoryQueryBus
    arguments: ['@customer.shared.QueryHandlers']
